services:
  - type: web
    name: Loic-Regresion-Logistica
    env: python
    buildCommand: pip install -r render_req.txt
    startCommand: python src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11