services:
  - type: web
    name: Loic-Regresion-Logistica
    env: python
    buildCommand: pip install -r render_req.txt
    startCommand: gunicorn app:app --chdir src
    envVars:
      - key: PYTHON_VERSION
        value: 3.11